dist: trusty
language: node_js
node_js:
   - "6.10.0"
sudo: false

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

branches:
  only:
    - master
    - dev
    - server-object-refactor
    - report-archive

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - export DATABASE=cognicity_server_testing ; git clone -b dev https://github.com/urbanriskmap/cognicity-schema.git urbanriskmap/cognicity-schema && cd urbanriskmap/cognicity-schema && bash build/run.sh && cd -

install:
  - npm install

after_success: npm run coverage
