language: node_js
node_js:
   - "6.10.0"
sudo: false

branches:
  only:
    - master
    - dev

notifications:

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

install:
  - npm install
