dist: precise
language: node_js
node_js:
   - "7"
sudo: true

addons:
  postgresql: "9.5"
services: postgresql

branches:
  only:
    - master
    - dev
    - server-object-refactor

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - git clone -b dev https://github.com/urbanriskmap/cognicity-schema.git urbanriskmap/cognicity-schema && cd urbanriskmap/cognicity-schema && bash build/run.sh && cd -

install:
  - npm install

after_success: npm run coverage
