language: node_js
node_js:
   - "6.10.0"
sudo: false

addons:
  postgresql: "9.4"
services: postgresql

branches:
  only:
    - master
    - dev

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - git clone git@github.com:urbanriskmap/cognicity-schema.git && bash cognicity-schema/build/run.sh

install:
  - npm install
